name: Tor VIP Clicker #3

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  gen-traffic:
    runs-on: ubuntu-latest
    container:
      image: python:3.8

      - name: Set up Tor SOCKS proxy
        run: |
          curl -sSLO https://raw.githubusercontent.com/dperson/torproxy/master/torproxy.sh
          chmod +x torproxy.sh
          ./torproxy.sh -l 9050 -i "0.0.0.0"


      - name: Run program
        run: |
          pip install selenium
          # Your Python script here
          python - <<'EOF'
          import time
          from selenium import webdriver

          urls = [
              "https://doruffleton.com/afu.php?zoneid=5995775&var=5995775&rid=XXz4jyvWNyEJSqRKY8d18w%3D%3D&rhd=false&os=windows&os_version=10.0.0",
              "https://doruffleton.com/afu.php?zoneid=5996161&var=5996161&rid=XXz4jyvWNyEJSqRKY8d18w%3D%3D&rhd=false&os=windows&os_version=10.0.0",
              "https://doruffleton.com/afu.php?zoneid=5996170&var=5996170&rid=XXz4jyvWNyEJSqRKY8d18w%3D%3D&rhd=false&os=windows&os_version=10.0.0",
              "https://doruffleton.com/afu.php?zoneid=5996172&var=5996172&rid=XXz4jyvWNyEJSqRKY8d18w%3D%3D&rhd=false&os=windows&os_version=10.0.0",
              "https://doruffleton.com/afu.php?zoneid=5996173&var=5996173&rid=XXz4jyvWNyEJSqRKY8d18w%3D%3D&rhd=false&os=windows&os_version=10.0.0",
              "https://doruffleton.com/afu.php?zoneid=5996174&var=5996174&rid=XXz4jyvWNyEJSqRKY8d18w%3D%3D&rhd=false&os=windows&os_version=10.0.0"
          ]

          options = webdriver.ChromeOptions()
          options.add_argument("--headless")  # Add this line to use Headless mode
          options.add_argument("--no-sandbox")  # Add this line to fix the sandbox error
          options.add_argument("--disable-dev-shm-usage")  # Add this line to fix the shm usage error

          driver = webdriver.Chrome(options=options)
          while True:
              for url in urls:
                  driver.get(url)
                  time.sleep(1)
              driver.quit()
              time.sleep(5)
          EOF
