on:
  schedule:
    - cron: "*/1 * * * *" # ทำงานทุก 1 นาที

jobs:
  gen-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate traffic
        env:
          HOST: ${{ secrets.HOST }}
        run: |
          urls=$(cat urls.txt)
          while true; do
            while IFS= read -r url; do
              echo "Making request to ${url}"
              response=$(curl -s -o /dev/null -w "%{http_code}" -A "Mozilla/5.0 (Android 12; Mobile; LG-M255; rv:100.0) Gecko/100.0 Firefox/100.0" "$url")
              if [ "$response" != "200" ]; then
                echo "❌ คำขอล้มเหลวด้วยสถานะ $response 😞"
                sleep 2
                continue
              fi
              echo "⏳ กำลังรอ 2 วินาทีก่อนที่จะสร้างคำขอใหม่... ⌛"
              sleep 2
            done <<< "$urls"
            sleep 5
          done
